name: pytest

on:
  push:
    branches:
      - "**"

  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: install just
        run: |
          curl --proto '=https' --tlsv1.2 --silent --show-error --fail https://just.systems/install.sh | bash -s -- --to ~/.local/bin

      - name: run test
        run: |
          ~/.local/bin/just test
